apiVersion: apps/v1
kind: Deployment
metadata:
  name: upspinner-example
  labels:
    app: upspinner-example
spec:
  selector:
    matchLabels:
      app: upspinner-example
  template:
    metadata:
      labels:
        app: upspinner-example
    spec:
      containers:
        - image: docker.pkg.github.com/tjipbv/upspinner-example/upspinner-example:c9cd999ccb410ca8bb31b2c92342c0b9702a9a10
          name: upspinner-example
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: upspinner-example
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: upspinner-example
  type: NodePort
